import {StyleSheet} from 'react-native'

const homeStyles=StyleSheet.create({
  container: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  SIcontainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  SUcontainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  uHcontainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  detailsScreencontainer: {
    flex: 1,
    backgroundColor: '#fff',
  },

  header:{
    padding: 46,
    alignSelf: 'stretch',
  },
  Homeheader:{
    paddingTop: 40,
    paddingLeft:20,
    paddingBottom:20,
    alignSelf: 'stretch',
  },
  SIheader:{
    alignSelf: 'stretch',
  },
  SUheader:{
    alignSelf: 'stretch',
  },
  uHheader:{
    alignSelf: 'stretch',
    padding: 10,
  },
  bespeaklogo:{
    color: '#eb9834',
    fontFamily: 'RedHatDisplay-Medium',
    fontSize: 30,
  },
  bespeaklogoWhite:{
    color: '#fff',
    fontFamily: 'RedHatDisplay-Regular',
    fontSize: 30,
  },
  sandboxtech:{
    fontSize:15,
    fontFamily: 'RedHatDisplay-Regular',
  },
  tabTitle:{
    color: '#eb9834',
    fontFamily: 'RedHatDisplay-Medium',
    fontSize: 25,
    marginLeft: '-35%',
  },
  goBack:{
    marginLeft: 10,
    width: 17,
    height: 17,
  },
  footer:{
    backgroundColor: '#eb9834',
    padding: 46,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  admitcontainer:{
    marginLeft:40,
    marginRight:40,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  SIfooter:{
    backgroundColor: '#ebebeb',
    padding: 46,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    flexDirection:'row',
  },
  SUfooter:{
    backgroundColor: '#ebebeb',
    padding: 46,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    flexDirection:'row',
  },
  searchfooter:{
    backgroundColor: '#ebebeb',
    padding: 46,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  ticketfooter:{
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  ATfooter:{
    backgroundColor: '#fff',
    padding: 46,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    flexDirection:'row',
  },

  uHfooter:{
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor:'#f5f5f5',
    alignItems: 'center',
    justifyContent: 'space-around',
    alignSelf: 'stretch',
    flexDirection: 'row',
  },
  homecontent:{
    backgroundColor:'#fff',
  },
  homeDetailsContainer:{
    backgroundColor:'#fff',
  },
  homeDetailsabtcontent:{
    paddingLeft: 20,
    paddingRight:20,
    backgroundColor:'#fff'
  },
  homeDetailscontent:{
    padding: 20,
  },
  homeDetailscontentTitle:{
    marginBottom:20,
    fontSize: 30,
    fontFamily: 'RedHatDisplay-Medium',
    color: '#000',
  },
  homeDetailscontentTime:{
    fontSize: 15,
    color: '#121212',
    fontFamily: 'RedHatDisplay-Light',    
  },
  homeDetailscontentDetails:{
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
    textAlign:'justify',
  },
  eventOrgOnContainerContent:{
    flexDirection:'row',
    justifyContent:'space-between',
    marginBottom:10,
  },
  eventOrgName:{
    fontSize: 22,
    fontFamily:'RedHatDisplay-Medium',
    color: '#000',
    marginLeft:3,
  },
  FollowOrg: {
    marginTop:-2,
    alignItems: 'center',
    backgroundColor: '#eb9834',
    height: 40,
    width: 120,
    padding: 10,
    borderRadius: 25,
    justifyContent:'center',
  },
  FollowOrgText:{
    marginTop: -2,
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Medium',
  },
  homeDetailsReminder:{
    color:'#000',
    fontFamily:'RedHatDisplay-Medium',
    fontSize: 25,
    marginBottom:5,
    marginTop:20,
  },
  homeDetailsAbout:{
    color:'#eb9834',
    fontFamily:'RedHatDisplay-Medium',
    fontSize: 25,
    marginBottom:5,
  },
  homeDetailscontentReminder:{
    color:'#000',
    fontFamily:'RedHatDisplay-Regular',
    fontSize: 17.5,
  },
  homeDetailscontentAbout:{
    color:'#000',
    fontFamily:'RedHatDisplay-Regular',
    fontSize: 17.5,
  },
  homeDetailscontentOnTime:{
    marginLeft:10,
    marginTop:3,
    marginBottom:20,
    fontSize: 16,
    color: '#121212',
    fontFamily: 'RedHatDisplay-Regular',    
  },
  homeDetailscontentOnLocation:{
    paddingRight:25,
    marginLeft:10,
    marginTop:1,
    marginBottom:20,
    fontSize: 16,
    color: '#121212',
    fontFamily: 'RedHatDisplay-Regular',    
  },


  notifcontent:{
    backgroundColor:'#fff',
    padding: 8,
  },
  notifimgContainer: {
    alignItems:'center',
    justifyContent:'center',
  },
  notifimg: {
    borderRadius:25,
    width: 50,
    height:50,
    justifyContent:'center',
  },
  fullnotifimgContainer: {
    alignItems:'center',
    justifyContent:'center',
  },
  fullnotifimg: {
    borderRadius:25,
    width: 40,
    height:40,
    justifyContent:'center',
  },
  texttext:{
    fontSize:16,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#000',
    fontFamily: 'RedHatDisplay-Regular',
    marginLeft: 50,
    padding: 5,
  },
  text:{
    fontSize:20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#000',
    fontFamily: 'RedHatDisplay-Regular',
    marginLeft: 20,
    padding: 10, 
  },
  titleText:{
    fontSize: 35,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#000',
    fontFamily: 'RedHatDisplay-Regular',
    padding: 10,
  },
  SItitleText:{
    marginTop: 10,
    fontSize: 35,
    color: '#000',
    fontFamily: 'RedHatDisplay-Medium',
    marginLeft: 40,
  },
  SUtitleText:{
    marginTop: 10,
    fontSize: 35,
    color: '#000',
    fontFamily: 'RedHatDisplay-Medium',
    marginLeft: 40,
  },
  ContinueAsbtncontainer:{
  borderWidth: 2,
  borderRadius: 8,
  borderColor: '#eb9834',
  flexDirection:'row',
  padding:10,
  marginTop:35,
  marginLeft:35,
  marginRight:35,
  },
  ContinueAsbtncontainerNotActive:{
    borderWidth: 2,
    borderRadius: 8,
    borderColor: '#f5f5f5',
    flexDirection:'row',
    padding:10,
    marginTop:35,
    marginLeft:35,
    marginRight:35,
    },
  IndivIcon:{
    padding:20,
    color:'#eb9834',
    backgroundColor: '#f5f5f5',
    borderRadius: 40,
    marginLeft:2,
  },
  IndivCard:{
    color: '#000',
    alignItems:'stretch',
    justifyContent:'space-between',
    alignSelf:'center',
    marginLeft:10,
  },
  IndivTitle:{
    fontSize: 20,
    fontFamily:'RedHatDisplay-Medium',
    color: '#000',
  },
  IndivText:{
    fontSize: 13,
    fontFamily:'RedHatDisplay-Light',
    color: '#000',
  },

  button: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#fff',
    height: 46,
    padding: 10,
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 5,
    color: '#fff',
  },
  buttonText:{
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#eb9834',
    fontFamily: 'RedHatDisplay-Regular',
  },
  button2: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#eb9834',
    height: 46,
    padding: 10,
    borderWidth: 2,
    borderColor: '#fff',
    borderRadius: 5,
  },
  buttonText2:{
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Regular',
  },
  admitbtn: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#eb9834',
    height: 46,
    padding: 10,
    borderWidth: 2,
    borderColor: '#fff',
    borderRadius: 25,
  },
  admitbtntxt:{
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Medium',
  },
  SIinput:{
    height: 46,
    borderBottomWidth: 1,
    marginLeft: 40,
    marginTop: 10,
    color: '#eb9834',
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
    marginRight: 40,
  },
  SUinput:{
    height: 46,
    borderBottomWidth: 1,
    marginTop: 10,
    marginLeft: 40,
    marginRight: 40,
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
    color: '#eb9834',
  },
  SIforgotpass:{
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 30,
    padding: 10,
    color: '#ccc',
    fontFamily: 'RedHatDisplay-Regular',
    fontSize: 16,
  },
  continuebtntext: {
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Regular',
  },
  continuebtn:{
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#eb9834',
    height: 48,
    padding: 10,
    borderWidth: 2,
    borderColor: '#fff',
    borderRadius: 15,
    marginLeft:110,
    marginRight:110,
    marginTop:40,
    marginBottom:80,
  },
  SIbutton: {
    alignSelf: 'stretch',
    height: 46,
    backgroundColor: '#eb9834',
    padding: 10,
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 5,
    color: '#eb9834',
    margin: 60,
    alignItems: 'center',
  },
  SIbuttonText:{
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Regular',
    fontSize: 20,
  },
  SUbuttonText:{
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Regular',
    fontSize: 20,
  },
  SUAltText:{
    fontSize: 16,
    justifyContent: 'center',
    marginLeft: 40,
    color: '#ccc',
    fontFamily: 'RedHatDisplay-Regular',
    alignItems: 'center',
  },
  Bbutton:{
    color: '#000',
    marginTop: 40,
    marginLeft: 20,
    marginBottom: 20,
    fontWeight: 'bold',
    fontSize: 35,
  },
  signup:{
    fontFamily: 'RedHatDisplay-Regular',
  },
  signin:{
    fontFamily: 'RedHatDisplay-Regular',
  },
  footerselectedIcon:{
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    padding: 10,
  },
  footerIcon:{
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
  },
  createcard:{
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#000',
    opacity:0.4,
    flexDirection: 'row',
    alignSelf:'stretch',
    justifyContent: 'space-between',
    padding: 2,
    margin: 10,
    marginLeft:20,
    marginRight:20,
    borderRadius: 35,
    flexDirection:'row',
  },
  card:{
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#f5f5f5',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    paddingLeft:20,
    paddingRight:20,
    width:'50%',
  },
  feed:{
    backgroundColor: '#f5f5f5',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginTop: '1.5%',
    marginLeft: '1%',
    marginRight: '1%',
    marginBottom: '1.5%',
    borderRadius: 20,
  },
  cardicon:{
    color: "#000",
    opacity:0.4,
    padding: 10, 
    fontSize: 20,
  },
  cardTitle:{
    color: "#eb9834",
    justifyContent: 'space-around',
    fontSize: 18,
    fontFamily: 'RedHatDisplay-Medium',
  },
  //...
  imgcontent:{
    width: 370,
    height: 130,
    backgroundColor:'#ccc',
    color:'black',
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Medium',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  //
  firstpic:{
    width: 370,
    height: 130,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  firstpiconmodal:{
    width: 412,
    height: 150,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  secondpic:{
    width: 370,
    height: 130,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  thirdpic:{
    width: 370,
    height: 130,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  picContainerOncontent:{
    
  },
  picOncontent:{
    width: 412,
    height: 180,
  },
  eventInfoTab:{
    padding: 10,
    marginLeft:10,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignSelf:'baseline',
    backgroundColor:'rgba(0,0,0,.5)',
  },
  modalView: {
    backgroundColor: "#fff",
    width: 412,
    height: 480,
    borderTopRightRadius: 40,
    borderTopLeftRadius: 40,
    alignItems: "center",
  },
  deletemodalView: {
    paddingTop:33,
    paddingLeft:10,
    backgroundColor: "#fff",
    width: 412,
    height: 120,
    borderTopRightRadius: 40,
    borderTopLeftRadius: 40,
  },
  deletebutton:{
    fontSize:20,
    paddingLeft:10,
    flexDirection:'row',
  },
  commentdateinfo:{
    marginTop:10,
    flexDirection:'row',
    marginLeft:3,
  },
  deleteText:{
    paddingLeft:10,
    color:'#000',
    fontSize:20,
    fontFamily:'RedHatDisplay-Regular'
  },
  commentdate:{
    paddingLeft:10,
    color:'#000',
    fontSize:20,
    fontFamily:'RedHatDisplay-Regular'
  },
  eventInfoOnmodal:{
    padding: 10,
    marginLeft: 5,
    marginRight: 5,
  },
  eventTitlecontent:{
    color: "#000",
    justifyContent: 'space-around',
    fontSize: 30,
    fontFamily: 'RedHatDisplay-Medium',
  },
  eventTitlecontentWhite:{
    paddingTop: 5,
    color: "#fff",
    fontSize: 30,
    fontFamily: 'RedHatDisplay-Medium',
  },
  feedcontentWhite:{
    marginBottom:5,
    color: "#fff",
    justifyContent: 'space-around',
    fontSize: 15,
    fontFamily: 'RedHatDisplay-Light',
  },
  eventTitlecontentOnmodal:{
    color: "#000",
    alignSelf:'center',
    justifyContent: 'center',
    fontSize: 28,
    marginBottom:12,
    fontFamily: 'RedHatDisplay-Medium',
  },
  eventDesccontentOnmodal:{
    color: "#000",
    fontSize: 17,
    fontFamily: 'RedHatDisplay-Regular',
  },
  eventDescTagcontentOnmodal:{
    marginTop: 10,
    marginBottom: 20,
    color: "#000",
    fontSize: 17,
    fontFamily: 'RedHatDisplay-Regular',
  },
  eventOrgOnmodal:{
    fontSize: 20,
    fontFamily:'RedHatDisplay-Medium',
    color: '#eb9834',
    marginLeft:3,
  },
  eventOrgIconOnmodal:{
    color:'#eb9834',
    backgroundColor: '#fff',
    borderRadius: 30,
    borderColor:'#eb8334',
    borderWidth: 1,
  },
  eventTabOnmodal:{
    flexDirection:'row',
    marginBottom:10,
  },
  joinTabOnmodal:{
    flexDirection:'row',
    justifyContent:'space-between',
    marginBottom: 12,
  },
  rowimgOnmodal:{
    flexDirection:'row',
  },
  othersInOnmodal: {
    alignItems: 'center',
    alignSelf: 'stretch',
    padding: 10,
    borderRadius: 25,
    flexDirection: 'column',
  },
  othersInTextOnmodal:{
    fontSize: 13,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#000',
    fontFamily: 'RedHatDisplay-Light',
  },
  imInOnmodal: {
    alignItems: 'center',
    backgroundColor: '#eb9834',
    height: 46,
    width: 150,
    padding: 10,
    borderRadius: 25,
    justifyContent:'center',
  },
  imInTextOnmodal:{
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Medium',
  },
  eventDTRcontent:{
    color: "#000",
    fontSize: 20,
    fontFamily: 'RedHatDisplay-Regular',
  },
  eventDTRcontentWhite:{
    marginTop:-2,
    color: "#fff",
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
  },
  eventLOCcontent:{
    color: "#eb9834",
    justifyContent: 'space-around',
    fontSize: 20,
    fontFamily: 'RedHatDisplay-Regular',
  },
  eventLOCcontentWhite:{
    paddingTop:10,
    color: "#fff",
    justifyContent: 'space-around',
    fontSize: 20,
    fontFamily: 'RedHatDisplay-Regular',
  },
  feedcontent:{
    color: "#000",
    justifyContent: 'space-around',
    fontSize: 14,
    fontFamily: 'RedHatDisplay-Light',
  },
  GeoLocTabcontent:{
    flexDirection:'row',
    alignContent:'center',
  },
  eventOptionTabcontent:{
    flexDirection:'row',
    alignContent:'center',
    justifyContent:'flex-end',
    marginBottom:10,
    marginRight: 10,
  },
  cardcontent:{
    color: "#000",
    justifyContent: 'space-around',
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Light',
  },
  createCardcontent:{
    width:300,
    color: "#000",
    justifyContent: 'space-around',
    fontSize: 16,
    padding:5,
    marginLeft:10,
    fontFamily: 'RedHatDisplay-Regular',
  },
  cardsearchheader:{
    padding:10,
    margin:10,
    backgroundColor: '#fff',
    borderRadius: 25,
    flexDirection:'row',
    marginTop: 40,
    borderColor:'#000',
    opacity:.5,
    borderWidth:1,
    marginLeft:20,
    marginRight:20,
  },
  notifHeader:{
    alignSelf: 'stretch',
    padding: 10,
    borderBottomColor:'#f5f5f5',
    borderWidth: 1,
  },
  searchbarIcon:{
    fontFamily: 'RedHatDisplay-Regular',
    color: '#000',
    marginLeft:5,
    color:'#eb9834',
  },

  searchBar:{
    flexDirection: 'row',
    fontFamily: 'RedHatDisplay-Regular',
    color: '#000',
    fontSize: 16,
    marginLeft:10,
    width:'100%',
  },
  scancontainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  scanText:{
    color: '#fff',
    padding: 10,
    backgroundColor: '#000',
    opacity:.1,
    alignSelf:'center',
    justifyContent:'center',
    margin:20,
    borderRadius: 10,
    fontSize:18,
    fontFamily:'RedHatDisplay-Light',
  },
  notifDates:{
    fontFamily: 'RedHatDisplay-Regular',
    fontSize: 20,
    color:'#eb9834',
    padding: 10,
  },
  notifTab:{
    flexDirection:'row',
    padding:10,
  },
  notifTabIcon:{
    color:'#eb9834',
    padding: 4,
    backgroundColor: '#fff',
    borderRadius: 30,
    borderColor:'#eb8334',
    borderWidth: 1,
    
    },
  notifCard:{
    fontSize: 15,
    fontFamily:'RedHatDisplay-Light',
    color: '#000',
    justifyContent:'center',
    alignSelf:'center',
    marginLeft:10,
  },
  notifContentName:{
    fontSize: 16,
    fontFamily:'RedHatDisplay-Medium',
    color: '#000',
    marginLeft:10,
  },
  notifContentPost:{
    fontSize: 16,
    fontFamily:'RedHatDisplay-Regular',
    color: '#000',
    marginLeft:10,
  },
  notifContentTime:{
    fontSize: 15,
    fontFamily:'RedHatDisplay-Light',
    color: '#000',
    marginLeft:10,
  },

  optiontabOne:{
    flexDirection:'row',
    padding: 2,
  },
  optionOne:{
    fontSize: 16,
    fontFamily:'RedHatDisplay-Medium',
  },
  seeoptionOne:{
    fontSize: 16,
    fontFamily:'RedHatDisplay-Medium',
  },
  dashboard:{
    marginTop: '1%',
    flexDirection:'row',
    alignItems: 'center'
  },
  counter:{
    flexDirection:'row',
    alignItems: 'center'
  },
  counterint:{
    flexDirection:'row', 
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily:'RedHatDisplay-Medium',
  },
  boardtextOne:{
    fontFamily:'RedHatDisplay-Regular',
    fontSize: 16,
    marginLeft: 5,
    marginRight:10,
    color: '#808080'
  },
  boardtextTwo:{
    fontFamily:'RedHatDisplay-Regular',
    fontSize: 16,
    marginLeft: 5,
    color: '#808080'
  },
  addbioarea:{
    padding: 20,
    margin: 20,
  },
  addbioTitle:{
    height: 46,
    marginTop: 10,
    marginLeft: 40,
    marginRight: 40,
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
    color: '#000',

  },
  addbiotext:{
    height: 46,
    marginTop: 10,
    marginLeft: 40,
    marginRight: 40,
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
    color: '#000',
  },
  eventIcon:{
    color:'#121212',
    backgroundColor:'#f5f5f5',
    padding: 10,
    borderWidth: 1,
    borderColor: '#eb9834',
    borderRadius: 25,
  },
  dropdown:{
  },
  dropdownlist:{
    alignSelf:'stretch',
    justifyContent:'space-between',
    flexDirection:'row',
    height: 46,
    borderBottomWidth: 1,
    marginTop: 10,
    marginLeft: 40,
    marginRight: 40,
    color: '#eb9834',
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
  },
  dropdowntext:{
    color: '#eb9834',
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
  },
  frontpic: {
    width: 412,
    height:520,
  },
  SampleQRpicContainer: {
    alignItems:'center',
    justifyContent:'center',
  },
  SampleQRpic: {
    width: 220,
    height:220,
    justifyContent:'center',
  },
  capicContainer: {
    alignItems:'center',
    justifyContent:'center',
  },
  capic: {
    marginBottom:10,
    width: 280,
    height:250,
    justifyContent:'center',
  },
  loginpicContainer: {
    alignItems:'center',
    justifyContent:'center',
  },
  loginpic: {
    marginBottom:10,
    width: 280,
    height:250,
    justifyContent:'center',
  },
  LetsGetStartedpicContainer:{
    marginTop:80,
    alignItems:'center',
    justifyContent:'center',
  },
  LetsGetStartedpic: {
    width: 280,
    height:250,
    justifyContent:'center',
  },
  AlmostTherepicContainer:{
    marginTop:80,
    alignItems:'center',
    justifyContent:'center',
  },
  AlmostTherepic: {
    width: 280,
    height:250,
    marginBottom:-30,
    justifyContent:'center',
  },
  hrtextcontainer:{
    backgroundColor:'#fff'
  },
  hrline:{
    borderBottomWidth:1,
    borderBottomColor: '#000',
    alignItems:'center',
    opacity: .2,
    marginTop: 5,
    paddingRight:20,
  },
  hrtext:{
    marginTop: -30,
    padding: 20,
    backgroundColor:'#fff',
    color:'#000',
    alignSelf:'center',
    fontSize:14,
  },
  commentBlock:{
    flexDirection:'row',
    paddingRight:20,
    justifyContent:'space-between',
    marginBottom:15,
  },
  MYcommentBlock:{
    flexDirection:'row',
    paddingRight:30,
    justifyContent:'space-between',
    marginBottom:15,
  },
  commentTab:{
    paddingLeft:10,
  },
  commentName:{
    paddingBottom:2,
    fontFamily:'RedHatDisplay-Medium',
    fontSize:18,
  },
  commentsays:{
    fontSize:15,
    width:280,
  },
  MYcommentsays:{
    fontSize:15,
    width:245,
    borderRadius:25,
    paddingLeft:10,
    height:35,
    backgroundColor:'#f5f5f5',
  },
  commentInfo:{
    paddingLeft:20,
  },
  attendingtab:{
    paddingTop:80,
    backgroundColor:'#fff',
    justifyContent:'center',
    marginBottom:5,
    paddingLeft:20,
    paddingRight:20,
  },
  attendingbutton: {
    marginTop:-2,
    alignItems: 'center',
    backgroundColor: '#eb9834',
    height: 40,
    padding: 10,
    borderRadius: 25,
    justifyContent:'center',
  },
  attendingtext:{
    marginTop: -2,
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Medium',
  },
  youresetView: {
    flex: 1,
    alignItems:'center',
    justifyContent: 'center',
    backgroundColor:'rgba(0,0,0,.1)',
  },
  youresetmodalView: {
    backgroundColor: "#fff",
    width: 300,
    height: 200,
    borderRadius:25,
    alignItems: "center",
  },
  okaybtn: {
    marginTop:8,
    alignItems: 'center',
    backgroundColor: '#eb9834',
    height: 40,
    width: 130,
    padding: 10,
    borderRadius: 25,
    justifyContent:'center',
  },
  okaybtntext:{
    marginTop: -2,
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Medium',
  },
  modaltxt:{
    fontSize:40,
    fontFamily:'RedHatDisplay-Medium',
    color:'#000',
    padding:15,
  },
  TicketContent:{
    flex:1,
    backgroundColor:'#eb9834',
  },
  YourTicket:{
    flex:1,
    backgroundColor:'#eb9834',
    alignItems:'center',
    justifyContent:'center',
  },
  YourTicketContent:{
    alignItems:'center',
    justifyContent:'center',
  },
  NameOnTicketWhite:{
    marginTop:5,
    color: '#fff',
    fontFamily: 'RedHatDisplay-Regular',
    fontSize: 25,
  },
  DateRegisteredWhite:{
    color: "#fff",
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
  },
  RefNumWhite:{
    marginTop:15,
    marginBottom:10,
    color: "#fff",
    justifyContent: 'space-around',
    fontSize: 15,
    fontFamily: 'RedHatDisplay-Light',
  },
  DetailscontentOnTicket:{
    marginTop:-30,
    marginLeft:60,
    marginRight:60,
    marginBottom:20,
    alignItems:'stretch',
    justifyContent:'flex-start',
  },
  contentDetailsOnTicket:{
    color:'#fff',
    fontFamily:'RedHatDisplay-Regular',
  },
  EventContainer:{
    marginTop:15,
    marginLeft:40,
    marginRight:40,
  },
  EventName:{
    fontFamily:'RedHatDisplay-Medium',
    fontSize:35,
    color:'#000',
  },
  EventDate:{
    fontFamily:'RedHatDisplay-Regular',
    fontSize:16,
    color:'#000',
  },
  EventOrganizer:{
    color:'#eb9834',
    fontSize:16,
    fontFamily:'RedHatDisplay-Regular',
  },
  TicketLocContainer:{
    flexDirection:'row',
    marginTop:2,
  },
  EventLocation:{
    marginTop:-1,
    fontSize:14,
    fontFamily:'RedHatDisplay-Light',
  },
  imgContainer: {
    alignItems:'center',
    padding:15,
  },
  imgscan: {
    width: 260,
    height: 260,
  },
  EventStat:{
    marginLeft:40,
    marginRight:40,
  },
  EventStattxt:{
    fontFamily:'RedHatDisplay-Medium',
    fontSize:35,
    color:'#eb9834',
  },
  TicketPersonalInfo:{
    marginTop:15,
    marginLeft:40,
    marginRight:40,
    opacity: .6
  },
  PersonName:{
    fontFamily:'RedHatDisplay-Medium',
    fontSize:25,
    color:'#000',
  },
  PersonEmail:{
    fontFamily:'RedHatDisplay-Regular',
    fontSize:15,
    color:'#000',
  },
  DateRegistered:{
    marginTop:1,
    fontFamily:'RedHatDisplay-Regular',
    fontSize:15,
    color:'#000',
  },
  profilecoverimgContainer: {
    alignItems:'center',
    justifyContent:'center',
  },
  profilecoverimg: {
    marginBottom:10,
    width: 412,
    height:150,
    justifyContent:'center',
  },
  Profileheader:{
    paddingTop: 40,
    alignSelf: 'stretch',
  },
  profileimgContainer: {
    marginLeft:20,
    marginTop:-47,
  },
  profileimg: {
    width: 70,
    height:70,
    borderRadius:40,
    borderWidth:1,
    borderColor:'#fff',
  },
  firstSection:{
    flexDirection:'row',
    justifyContent:'space-between',
  },
  EditProfile: {
    marginTop:-2,
    marginRight:20,
    alignItems: 'center',
    backgroundColor: '#eb9834',
    height: 35,
    width: 120,
    padding: 10,
    borderRadius: 25,
    justifyContent:'center',
  },
  EditProfileText:{
    marginTop: -2,
    fontSize: 15,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Medium',
  },
  secondSection:{
    marginLeft:15,
    marginRight:15,
  },
  ProfileName:{
    fontFamily:'RedHatDisplay-Medium',
    fontSize:23,
  },
  ProfileBio:{
    fontFamily:'RedHatDisplay-Regular',
    fontSize:16,
    marginBottom: '1%',
    marginTop: '1%',
  },
  ProfileLocation:{
    fontFamily:'RedHatDisplay-Medium',
    fontSize:16,
    marginLeft: 5,
    color: '#808080'
  },
  editProfileheader:{
    paddingTop: 40,
    alignSelf: 'stretch',
    flexDirection:'row',
    justifyContent:'space-between',
  },
  profileimgContainer: {
    marginLeft:20,
    marginTop:-47,
  },
  profileimg: {
    width: 70,
    height:70,
    borderRadius:40,
    borderWidth:1,
    borderColor:'#fff',
  },
  tabSave:{
    marginTop:4,
    color: '#eb9834',
    fontFamily: 'RedHatDisplay-Medium',
    fontSize: 18,
    marginRight:20,
    fontWeight: 'bold'
  },
  editprofilecoverimgContainer: {
    alignItems:'center',
    justifyContent:'center',
  },
  editprofilecoverimg: {
    marginBottom:10,
    width: 412,
    height:150,
    justifyContent:'center',
    opacity:0.4
  },
  editprofileimgContainer: {
    marginLeft:20,
    marginTop:-47,
  },
  editprofileimg: {
    width: 70,
    height:70,
    borderRadius:40,
    borderWidth:1,
    borderColor:'#fff',
    opacity:.7
  },
  editcoverimg:{
    color: '#000', 
    fontSize: 20,
    alignItems:'center',
    position:'absolute',
  },
  editimg:{
    color: '#000', 
    fontSize: 20,
    position:'absolute',
    marginTop:'35%',
    marginLeft:'35%',
  },
  changepw: {
    alignSelf: 'stretch',
    height: 46,
    backgroundColor: '#eb9834',
    padding: 10,
    borderRadius: 25,
    color: '#eb9834',
    marginTop:50,
    marginLeft: 20,
    marginRight: 20,
    alignItems: 'center',
  },
  changepwtxt:{
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Medium',
    fontSize: 20,
  },
  signout: {
    alignSelf: 'stretch',
    height: 46,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 25,
    color: '#eb9834',
    marginTop:10,
    marginLeft: 100,
    marginRight: 100,
    alignItems: 'center',
  },
  signouttxt:{
    alignItems: 'center',
    justifyContent: 'center',
    color: '#eb9834',
    fontFamily: 'RedHatDisplay-Medium',
    fontSize: 20,
  },
  
  Info:{
    alignItems: 'center',
    justifyContent: 'center',
    marginTop:20,
    marginLeft: 20,
    color: '#ccc',
    fontFamily: 'RedHatDisplay-Regular',
    fontSize: 16,
  },
  Profileinput:{
    height: 46,
    borderBottomWidth: 1,
    marginLeft: 20,
    marginRight: 20,
    fontSize: 16,
    fontFamily: 'RedHatDisplay-Regular',
    color: '#eb9834',
  },
  createEventheader:{
    paddingTop: 40,
    alignSelf: 'stretch',
    paddingBottom:10,
    borderBottomColor:'#f5f5f5',
    borderBottomWidth:1,
    flexDirection:'row',
  },
  YourTickettxt:{
    fontFamily:'RedHatDisplay-Medium',
    marginLeft:10,
    fontSize: 24,
    color:'#eb9834',
    marginTop:-6,
  },
  createevent: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#eb9834',
    height: 46,
    padding: 10,
    marginLeft:20,
    marginRight:20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 25,
    color: '#fff',
  },
  createeventtxt:{
    fontSize: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontFamily: 'RedHatDisplay-Medium',
  },
  addimgcontainer:{
    alignItems:'center',
    justifyContent:'center',
  },
  
  addimgicon:{
    alignItems:'center',
    justifyContent:'center',
    color: '#000', 
    fontSize: 20,
    backgroundColor:'#ddd',
    width:380,
    height:150,
    marginTop:10,
    marginLeft:20,
    marginRight:20,
    borderRadius:10,
  },
  addbannercoverimgContainer: {
    alignItems:'center',
    justifyContent:'center',
    marginTop:10,
    marginLeft:20,
    marginRight:20,
  },
  addbannerimg:{
    color: '#000', 
    fontSize: 20,
    alignItems:'center',
    position:'absolute',
  },
  addbannercoverimg: {
    marginBottom:10,
    width: 368,
    height:150,
    justifyContent:'center',
    backgroundColor: 'rgba(221, 221, 221, 0.5)',
    borderRadius: 10,
  },
  createeventcontainer:{
    margin:20,
  },
  eventCreatetxt:{
    fontFamily:'RedHatDisplay-Medium',
    fontSize:30,
  },
  CreateEventNamecontainer:{
    marginLeft: 20,
    marginRight: 20,
    flexDirection:'row',
    backgroundColor: 'rgba(221, 221, 221, 0.5)',
    borderRadius:10,
    marginBottom:15,
  },
  CreateEventNameIcon:{
    color:'#000',
    opacity: .5,
    marginLeft:10,
    marginTop:10
  },
  CreateEventNameField:{
    fontSize:16,
    fontFamily:'RedHatDisplay-Regular',
    marginLeft: 10,
    marginRight: 20,
    flexDirection:'row',
    marginTop:-3,
    padding:10,
  },
  CreateEventSchedcontainer:{
    marginLeft: 20,
    marginRight: 20,
    flexDirection:'row',
    backgroundColor: 'rgba(221, 221, 221, 0.5)',
    borderRadius:10,
    marginBottom:15,
  },
  CreateEventSchedIcon:{
    color:'#000',
    opacity: .5,
    marginLeft:10,
    marginTop:10,
  },
  CreateEventSchedField:{
    fontSize:16,
    fontFamily:'RedHatDisplay-Regular',
    marginLeft: 12,
    marginRight: 20,
    flexDirection:'row',
    marginTop:-3,
    padding:10,
  },
  CreateEventDesccontainer:{
    marginLeft: 20,
    marginRight: 20,
    flexDirection:'row',
    backgroundColor: 'rgba(221, 221, 221, 0.5)',
    borderRadius:10,
    marginBottom:15,
  },
  CreateEventDescIcon:{
    color:'#000',
    opacity: .5,
    marginLeft:10,
    marginTop:10,
  },
  CreateEventDescField:{
    fontSize:16,
    fontFamily:'RedHatDisplay-Regular',
    marginLeft: 12,
    marginRight: 20,
    flexDirection:'row',
    marginTop:-3,
    padding:10,
  },
  MyTabsContainer:{
    justifyContent:'space-around',
    flexDirection:'row',
    padding:10,
    borderBottomWidth: 1.5,
    borderBottomColor: '#ddd',
  },
  MyTabs:{
    alignSelf:'stretch',
    fontSize:18,
    fontFamily:'RedHatDisplay-Regular',
  },
  MyTabsSelect:{
    borderBottomWidth:4,
    borderBottomColor:'#eb9834',
    marginBottom:-10
  },
  MyTicketStub:{
    margin:20,
    borderRadius:20,
    backgroundColor:'#eb9834',
    width: 370,
    height: 140,
  },
  MyTicketStubDiv:{
    margin:20,
    flexDirection:'row',
    justifyContent:'space-between'
  },
  MyTicketEvent:{
    color:'#fff',
    fontSize:23,
    fontFamily:'RedHatDisplay-Medium',
  },
  MyTicketDate:{
    color:'#fff',
    fontSize:15,
    marginBottom:10,
    fontFamily:'RedHatDisplay-Light',
  },
  MyTicketOrganizer:{
    color:'#fff',
    fontSize:20,
    fontFamily:'RedHatDisplay-Medium',
  },
  MyTicketLocation:{
    color:'#fff',
    fontSize:15,
    fontFamily:'RedHatDisplay-Light',
  },
  MyTicketQRContainer:{
    borderRadius:20,
    width: 100,
    height: 100,
  },
  MyTicketQR:{
    borderRadius: 15,
    width: 100,
    height: 100,
  },
  LocationContainer: {
    flexDirection:'row',
    alignItems: 'center',
    color: '#808080',
    marginTop: '4%'
  },
  defaultInputStandardContainer:{
    marginLeft:'10%',
    marginRight:'10%',
    marginTop:'4%',
    height:'4%',
  },
  defaultNextInputStandardContainer:{
    marginLeft:'10%',
    marginRight:'10%',
    marginTop:'2.5%',
    height:'4%',
  },
})

export default homeStyles;